In [1]:
import pandas as pd

In [2]:
# Retreiving the data file

df = pd.read_csv('yelp.csv')
df.dropna()

business_id        date               review_id  stars  \
0     9yKzy9PApeiPPOUJEtnvkg  2011-01-26  fWKvX83p0-ka4JS3dc6E5A      5   
1     ZRJwVLyzEJq1VAihDhYiow  2011-07-27  IjZ33sJrzXqU-0X6U8NwyA      5   
2     6oRAC4uyJCsJl1X0WZpVSA  2012-06-14  IESLBzqUCLdSzSqm0eCSxQ      4   
3     _1QQZuf4zZOyFCvXc0o6Vg  2010-05-27  G-WvGaISbqqaMHlNnByodA      5   
4     6ozycU1RpktNG2-1BroVtw  2012-01-05  1uJFq2r5QfJG_6ExMRCaGw      5   
...                      ...         ...                     ...    ...   
9995  VY_tvNUCCXGXQeSvJl757Q  2012-07-28  Ubyfp2RSDYW0g7Mbr8N3iA      3   
9996  EKzMHI1tip8rC1-ZAy64yg  2012-01-18  2XyIOQKbVFb6uXQdJ0RzlQ      4   
9997  53YGfwmbW73JhFiemNeyzQ  2010-11-16  jyznYkIbpqVmlsZxSDSypA      4   
9998  9SKdOoDHcFoxK5ZtsgHJoA  2012-12-02  5UKq9WQE1qQbJ0DJbc-B6Q      2   
9999  pF7uRzygyZsltbmVpjIyvw  2010-10-16  vWSmOhg2ID1MNZHaWapGbA      5   

                                                   text    type  \
0     My wife took me here on my birthday for breakf...  review   
1     I have no idea why some people give bad review...  review   
2     love the gyro plate. Rice is so good and I als...  review   
3     Rosie, Dakota, and I LOVE Chaparral Dog Park!!...  review   
4     General Manager Scott Petello is a good egg!!!...  review   
...                                                 ...     ...   
9995  First visit...Had lunch here today - used my G...  review   
9996  Should be called house of deliciousness!\n\nI ...  review   
9997  I recently visited Olive and Ivy for business ...  review   
9998  My nephew just moved to Scottsdale recently so...  review   
9999  4-5 locations.. all 4.5 star average.. I think...  review   

                     user_id  cool  useful  funny  
0     rLtl8ZkDX5vH5nAx9C3q5Q     2       5      0  
1     0a2KyEL0d3Yb1V6aivbIuQ     0       0      0  
2     0hT2KtfLiobPvh6cDC8JQg     0       1      0  
3     uZetl9T0NcROGOyFfughhg     1       2      0  
4     vYmM4KTsC8ZfQBg-j5MWkw     0       0      0  
...                      ...   ...     ...    ...  
9995  _eqQoPtQ3e3UxLE4faT6ow     1       2      0  
9996  ROru4uk5SaYc3rg8IU7SQw     0       0      0  
9997  gGbN1aKQHMgfQZkqlsuwzg     0       0      0  
9998  0lyVoNazXa20WzUyZPLaQQ     0       0      0  
9999  KSBFytcdjPKZgXKQnYQdkA     0       0      0  

[10000 rows x 10 columns]

In [3]:
# Tokenizing the input with various stop words

from nltk.stem import PorterStemmer
from nltk.tokenize import RegexpTokenizer
import nltk
#nltk.download('punkt')
tokenizer = RegexpTokenizer(r'\w+')
ps = PorterStemmer()

temp = []
stopWords = ['a', 'the', 'is', 'are', '\n', "'s"]
newDF = pd.DataFrame(columns = ['Review','Rating'])


for idx, row in df.iterrows():
    rating = row['stars']
    rev = row['text']
    rev = tokenizer.tokenize(rev)
    for word in rev:
        if word.lower() not in stopWords:
            if word == "'t":
                temp.append('not')
            elif word == "'m":
                temp.append('am')
            else:
                temp.append(ps.stem(word))
    new_data = pd.DataFrame({'Review': [temp], 'Rating': [rating]})
    #print(new_data)
    newDF = pd.concat([newDF, new_data], axis=0)
    #newDF = pd.concat({'Review':temp,'Rating':rating},ignore_index=True)
    temp = []
# In the forum of an array [[sent1], [sent2], ...] -> sentences are separated into words ['word1', 'word2', ...]

In [4]:
# Creating the vocabulary, mapping each word to a unique index

# Structure of newDF => Review | Rating
#print(newDF['Review'][:5])
vocab = {}
idx = 1
maxlen = 0
for seq in newDF['Review']:
    maxlen = max(len(seq),maxlen)
    for word in seq:
        if word not in vocab:
            vocab[word] = idx
            idx+=1
print(vocab)

{'my': 1, 'wife': 2, 'took': 3, 'me': 4, 'here': 5, 'on': 6, 'birthday': 7, 'for': 8, 'breakfast': 9, 'and': 10, 'it': 11, 'wa': 12, 'excel': 13, 'weather': 14, 'perfect': 15, 'which': 16, 'made': 17, 'sit': 18, 'outsid': 19, 'overlook': 20, 'their': 21, 'ground': 22, 'an': 23, 'absolut': 24, 'pleasur': 25, 'our': 26, 'waitress': 27, 'food': 28, 'arriv': 29, 'quickli': 30, 'semi': 31, 'busi': 32, 'saturday': 33, 'morn': 34, 'look': 35, 'like': 36, 'place': 37, 'fill': 38, 'up': 39, 'pretti': 40, 'so': 41, 'earlier': 42, 'you': 43, 'get': 44, 'better': 45, 'do': 46, 'yourself': 47, 'favor': 48, 'bloodi': 49, 'mari': 50, 'phenomen': 51, 'simpli': 52, 'best': 53, 'i': 54, 've': 55, 'ever': 56, 'had': 57, 'm': 58, 'sure': 59, 'they': 60, 'onli': 61, 'use': 62, 'ingredi': 63, 'from': 64, 'garden': 65, 'blend': 66, 'them': 67, 'fresh': 68, 'when': 69, 'order': 70, 'amaz': 71, 'while': 72, 'everyth': 73, 'menu': 74, 'white': 75, 'truffl': 76, 'scrambl': 77, 'egg': 78, 'veget': 79, 'skillet': 

In [5]:
# Encoded Input will be used for training the model, it is padded with zeros

import numpy as np

EncodedInput = np.zeros((len(newDF),maxlen), dtype = 'int32')
rowIdx = 0
colIdx = 0
for seq in newDF['Review']:
    for word in seq:
        EncodedInput[colIdx,rowIdx] = vocab[word]
        rowIdx += 1
    rowIdx = 0
    colIdx += 1
# word coded arr in row and col per review

In [6]:
# checks vocab is right and no dupe words

num = 1
checker = set()
for key,val in vocab.items():
    if val != num or key in checker:
        print('error')
    checker.add(key)
    num += 1
print('done')
print(checker)

done
{'stair', 'confect', 'trampolin', 'giro', 'mush', 'rider', 'each', 'deschut', 'fijita', 'ah', 'hinder', 'cargo', 'telegraph', 'hanni', 'mindblow', 'wre', 'gossip', 'mashup', 'wrangl', 'penal', 'mi', 'grr', 'moviego', '2600', 'boolgoge', 'pacif', 'ram', 'sacrif', 'inth', 'teeth', 'rewind', 'raw', 'shell', 'eateri', 'oxtail', 'danni', 'balthazar', '105', 'taco', 'taster', 'snooz', 'gal', 'heff', 'nonverb', 'raj', 'gestur', 'whatev', '2005', 'cheek', 'mignon', 'garish', 'humbolt', 'studio', 'staircas', 'offici', 'restless', 'mcgaee', 'butterfish', 'gym', 'pam', 'caico', 'deadli', 'morman', 'kidless', 'bookmark', 'tgf', 'somewhat', 'classroom', 'review', 'comic', 'longest', 'as', 'opp', 'brainwash', 'ooo', 'unnotic', 'franco', 'alfredo', 'hop', 'leguizamo', 'kruger', 'discreet', 'snarf', 'autograph', 'reparte', 'champagn', 'highway', 'shouldn', 'nametag', 'lego', 'bland', 'barrier', 'buffet', 'unanim', 'showroom', 'wolf', 'celebratori', 'wordi', 'vicin', 'ackward', 'dominiqu', 'yelpit

In [7]:
# Creates a NumPy array of the ratings (1,2,3,4,5)

RatingOutput = np.zeros((len(newDF),1), dtype = 'int8')
idx = 0
for rating in newDF['Rating']:
    RatingOutput[idx,0] = rating
    idx+=1
# 1 col of ratings, 1 elemnt per row

In [8]:
# Creating new corpus that uses the words' indices opposed to the word itself, not padded used for the embeddings

SentCorpus = []
temp = []
corpus = newDF['Review']
for sent in corpus:
    for word in sent:
        temp.append(vocab[word])
    SentCorpus.append(temp)
    temp = []

In [9]:
# Training the word embeddings for the data set

from gensim.models import Word2Vec
# Initialize and train Word2Vec model
model = Word2Vec(sentences=SentCorpus, window=10, min_count=1, vector_size=10)
model.train(SentCorpus, total_examples=len(corpus), epochs=10)

# Access trained word embeddings
embeddings = model.wv

In [ ]:
# Testing the embeddings
embeddings.most_similar(positive=['good','quick','nice','delic'], negative=['bad','rude'])

In [ ]:
# Apply clustering to the embedded words so you can see how the words are grouped, not necessary for training
from sklearn.preprocessing import normalize
from sklearn.cluster import KMeans
from gensim.models import Word2Vec
import numpy as np

import warnings
# warnings.filterwarnings("ignore")

#Apply K-means clustering
num_clusters = 5  # Specify the desired number of clusters
kmeans = KMeans(n_clusters=num_clusters, random_state=42, n_init=10)

import os
os.environ["OMP_NUM_THREADS"] = "1"

warnings.filterwarnings("ignore", category=FutureWarning)

normalized_embeddings = np.linalg.norm(embeddings.vectors, axis=1, keepdims=True)
normalized_embeddings = embeddings / normalized_embeddings
# print(normalized_embeddings.shape)
# print(model.vector_size)
# print(np.isnan(normalized_embeddings).any())
print(kmeans)
cluster_labels = kmeans.fit_predict(normalized_embeddings)
words = model.wv.index_to_key
for word, label in zip(words, cluster_labels):
    print(f"{word}: Cluster {label}")

import matplotlib.pyplot as plt

# Create a scatter plot
plt.scatter(normalized_embeddings[:, 0], normalized_embeddings[:, 1], c=cluster_labels)
plt.xlabel('Dimension 1')
plt.ylabel('Dimension 2')
plt.title('Cluster Labels')
plt.show()

In [ ]:
# Save the embedding model that stores each word as their index in the vocab dictionary
model.save('EmbeddingsIDXModel')

In [10]:
# One-hot encoding the outputs
Output = [0] * len(RatingOutput)
for index in range(len(RatingOutput)):
    if RatingOutput[index] == 1:
        Output[index] = [1, 0, 0, 0, 0]
    elif RatingOutput[index] == 2:
        Output[index] = [0, 1, 0, 0, 0]
    elif RatingOutput[index] == 3:
        Output[index] = [0, 0, 1, 0, 0]
    elif RatingOutput[index] == 4:
        Output[index] = [0, 0, 0, 1, 0]
    else:
        Output[index] = [0, 0, 0, 0, 1]
Output = np.array(Output)

In [11]:
# print(EncodedInput)
# print(RatingOutput)
# Input in the form of each word has an index in a dict and 
# they are converted to numbers, padded to the length of the longest review
# Output is each row is the value of the review for the given review in its same row
# Len of data set is 10000

X_Train = EncodedInput[:9000]
Y_Train = Output[:9000]
X_Test = EncodedInput[9000:]
Y_Test = Output[9000:]

In [12]:
# Checking if the processed data is correct
for sent1, sent2 in zip(EncodedInput,corpus):
    for word1,word2 in zip(sent1,sent2):
        if word1 != vocab[word2]:
            print("ERROR")
            break
print('Done')

Done


In [13]:
# Checking if the output one-hot encoded correctly
for arr1, out in zip(Output, RatingOutput):
    if arr1[out[0]-1] != 1:
        print("ERROR")
print('Done')

Done


In [ ]:
# wife and husband have very similar meanings
print(embeddings.most_similar(0))
print(vocab)

In [26]:
from keras.models import Sequential
from keras.layers import Embedding, LSTM, Dense, Masking, SimpleRNN, Dropout
import keras
import tensorflow
from keras.regularizers import l2
from keras.initializers import RandomNormal


#256
num_hidden_units = 256
optimizer = keras.optimizers.Adam(learning_rate=0.005) #changed from .001 to .005
l2_regularization = 0.01

embeddings1 = np.array(embeddings)

#print(np.shape(embeddings.vectors))

# Define the RNN model
modelRegressor = Sequential()
modelRegressor.add(Embedding(input_dim=len(vocab), output_dim=10, input_length=maxlen, weights=[embeddings.vectors], mask_zero=True))
modelRegressor.add(LSTM(units=num_hidden_units))

#Removed
#modelRegressor.add(Dropout(0.2))

#model1.add(Masking(mask_value=0))  # Masking zero-padded sequences
#softmax -> sigmoid
modelRegressor.add(Dense(units=1, activation='relu', kernel_regularizer=l2(l2_regularization), kernel_initializer='random_normal'))

# Compile the model
modelRegressor.compile(loss='mean_squared_error', optimizer=optimizer, metrics=['mse'])

# Print the model summary
modelRegressor.summary()

Model: "sequential_6"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_6 (Embedding)     (None, 899, 10)           202630    
                                                                 
 lstm_6 (LSTM)               (None, 256)               273408    
                                                                 
 dense_6 (Dense)             (None, 1)                 257       
                                                                 
Total params: 476295 (1.82 MB)
Trainable params: 476295 (1.82 MB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [25]:
from keras.models import Sequential
from keras.layers import Embedding, LSTM, Dense, Masking, SimpleRNN, Dropout
import keras
import tensorflow
from keras.regularizers import l2
from keras.initializers import RandomNormal


#256
num_hidden_units = 256
optimizer = keras.optimizers.Adam(learning_rate=0.005) #changed from .001 to .005
l2_regularization = 0.01

embeddings1 = np.array(embeddings)


# Define the RNN model
modelClassifier = Sequential()
modelClassifier.add(Embedding(input_dim=len(vocab), output_dim=10, input_length=maxlen, weights=[embeddings.vectors], mask_zero=True))
modelClassifier.add(LSTM(units=num_hidden_units))
modelClassifier.add(Dropout(0.2))
#model1.add(Masking(mask_value=0))  # Masking zero-padded sequences
#softmax -> sigmoid
modelClassifier.add(Dense(units=5, activation='softmax', kernel_regularizer=l2(l2_regularization), kernel_initializer='random_normal'))

# Compile the model
modelClassifier.compile(loss='categorical_crossentropy', optimizer=optimizer, metrics=['accuracy'])

# Print the model summary
modelClassifier.summary()

Model: "sequential_5"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_5 (Embedding)     (None, 899, 10)           202630    
                                                                 
 lstm_5 (LSTM)               (None, 256)               273408    
                                                                 
 dropout_4 (Dropout)         (None, 256)               0         
                                                                 
 dense_5 (Dense)             (None, 5)                 1285      
                                                                 
Total params: 477323 (1.82 MB)
Trainable params: 477323 (1.82 MB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [17]:
# Train the RNN models
num_epochs = 10
batch_size = 32


Y_TrainR = RatingOutput[:9000]
print('~~~~~~~~~~~~~~~~~~~~~~~~~~~')
print('Training the Classifier Model')
historyClassifier = modelClassifier.fit(X_Train, Y_Train, batch_size=batch_size, epochs=num_epochs, validation_split=0.1, shuffle=True)
print('~~~~~~~~~~~~~~~~~~~~~~~~~~~')
print('Training the Regressor Model')
historyRegressor = modelRegressor.fit(X_Train, Y_TrainR, batch_size=batch_size, epochs=num_epochs, validation_split=0.1, shuffle=True)

~~~~~~~~~~~~~~~~~~~~~~~~~~~
Training the Classifier Model
Epoch 1/10
254/254 [==============================] - 234s 910ms/step - loss: 1.4414 - accuracy: 0.3491 - val_loss: 1.4283 - val_accuracy: 0.3556
Epoch 2/10
254/254 [==============================] - 194s 763ms/step - loss: 1.3843 - accuracy: 0.3784 - val_loss: 1.3336 - val_accuracy: 0.3956
Epoch 3/10
254/254 [==============================] - 196s 769ms/step - loss: 1.2788 - accuracy: 0.4311 - val_loss: 1.2960 - val_accuracy: 0.4311
Epoch 4/10
254/254 [==============================] - 214s 844ms/step - loss: 1.1423 - accuracy: 0.4907 - val_loss: 1.2396 - val_accuracy: 0.4344
Epoch 5/10
254/254 [==============================] - 208s 819ms/step - loss: 1.0362 - accuracy: 0.5595 - val_loss: 1.2448 - val_accuracy: 0.4600
Epoch 6/10
254/254 [==============================] - 207s 813ms/step - loss: 0.9295 - accuracy: 0.6165 - val_loss: 1.2895 - val_accuracy: 0.4433
Epoch 7/10
254/254 [==============================] - 210s 825ms/s

In [ ]:
# Check to make sure you can achieve the embedding for any word in the vocab


# Get the word index for the word you want to retrieve the embedding
word = 'wife'
word_index = vocab[word]

# Get the embedding layer from the model
embedding_layer = model1.layers[0]

# Get the learned embedding matrix (weights) from the embedding layer
embedding_matrix = embedding_layer.get_weights()[0]

# Look up the word embedding vector from the embedding matrix
word_embedding = embedding_matrix[word_index]

print(f"Embedding vector for '{word}':\n{word_embedding}")
print(embedding_matrix[0])
print(embedding_matrix)

In [18]:
# Access the training history

training_lossR = historyRegressor.history['loss']
training_accuracyR = historyRegressor.history['mse']
validation_lossR = historyRegressor.history['val_loss']
validation_accuracyR = historyRegressor.history['val_mse']

training_loss = historyClassifier.history['loss']
training_accuracy = historyClassifier.history['accuracy']
validation_loss = historyClassifier.history['val_loss']
validation_accuracy = historyClassifier.history['val_accuracy']

# Print the training and validation metrics
print("~~~~~~~~~~~~~~~~~~~~~~~~~~")
print("Classifier Model Metrics")
print("Training Loss:", training_loss)
print("Training Accuracy:", training_accuracy)
print("Validation Loss:", validation_loss)
print("Validation Accuracy:", validation_accuracy)

print("~~~~~~~~~~~~~~~~~~~~~~~~~~")
print("Regression Model Metrics")
print("Training Loss:", training_lossR)
print("Training Accuracy:", training_accuracyR)
print("Validation Loss:", validation_lossR)
print("Validation Accuracy:", validation_accuracyR)

~~~~~~~~~~~~~~~~~~~~~~~~~~
Classifier Model Metrics
Training Loss: [1.4413974285125732, 1.3842799663543701, 1.278844952583313, 1.142311692237854, 1.036234736442566, 0.9295136332511902, 0.8287171721458435, 0.7451557517051697, 0.6962130665779114, 0.6027688384056091]
Training Accuracy: [0.3491358160972595, 0.37839505076408386, 0.43111109733581543, 0.49074074625968933, 0.5595061779022217, 0.6165432333946228, 0.6781481504440308, 0.7169135808944702, 0.7423456907272339, 0.7943210005760193]
Validation Loss: [1.4283416271209717, 1.3336281776428223, 1.2959797382354736, 1.239626169204712, 1.2448362112045288, 1.2894524335861206, 1.2927602529525757, 1.3682740926742554, 1.4291349649429321, 1.4295988082885742]
Validation Accuracy: [0.35555556416511536, 0.3955555558204651, 0.43111109733581543, 0.43444445729255676, 0.46000000834465027, 0.44333332777023315, 0.47777777910232544, 0.4722222089767456, 0.46666666865348816, 0.4588888883590698]
~~~~~~~~~~~~~~~~~~~~~~~~~~
Regression Model Metrics
Training Loss:

In [22]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

# Utilizing the models and making predictions
test_predictionsR = modelRegressor.predict(X_Test[:10])
test_predictions = modelClassifier.predict(X_Test[:10])
print(test_predictionsR)
print(test_predictions)
print(Y_Test[:10])
print(softMax(test_predictions,Y_Test[:10]))
print(calcRating(test_predictions,Y_Test[:10]))

# # Calculate evaluation metrics
# accuracy = accuracy_score(Y_Test, test_predictions)
# precision = precision_score(Y_Test, test_predictions, average='weighted')
# recall = recall_score(Y_Test, test_predictions, average='weighted')
# f1 = f1_score(Y_Test, test_predictions, average='weighted')

# # Print the evaluation metrics
# print("Accuracy:", accuracy)
# print("Precision:", precision)
# print("Recall:", recall)
# print("F1-score:", f1)


1/1 [==============================] - 0s 102ms/step
[[2.8157308]
 [3.4859285]
 [3.885545 ]
 [3.2606966]
 [4.105384 ]
 [3.1522844]
 [3.7385125]
 [3.4133542]
 [3.254051 ]
 [4.4355125]]
[[6.0671881e-02 9.5320933e-02 5.0988483e-01 2.6754737e-01 6.6574968e-02]
 [2.1253573e-03 4.3463227e-03 3.5433944e-02 8.8409734e-01 7.3997103e-02]
 [7.7847824e-02 8.0538392e-02 1.1324934e-01 1.8760042e-01 5.4076409e-01]
 [3.5786472e-02 2.2143209e-01 4.9334341e-01 1.8730415e-01 6.2134005e-02]
 [7.3688215e-04 1.1945372e-03 8.3670719e-03 8.4004122e-01 1.4966020e-01]
 [5.1351923e-01 3.9375210e-01 6.1954927e-02 1.3157505e-02 1.7616251e-02]
 [5.6828833e-01 2.4184927e-01 1.3244380e-01 4.2568196e-02 1.4850390e-02]
 [4.0640258e-03 4.2594424e-03 1.5797978e-02 7.4881446e-01 2.2706422e-01]
 [2.8171742e-02 7.7594392e-02 4.6307391e-01 3.9404958e-01 3.7110411e-02]
 [1.0989080e-03 1.5123538e-03 1.3395327e-03 4.8058353e-02 9.4799083e-01]]
[[0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]
 [0 1 0 0 0]
 [0 1 0 0 0]
 [0 1 0 0 0]
 [1 0 0

In [20]:
# Function used to find the largest value in the array of 5 values
def softMax(arr, true):
    trueidx = 0
    for row in arr:
        temp = max(row)
        idx = 1
        print('Sample:', trueidx)
        for el in row:
            if el == temp:
                print('Guess:',idx)
                break
            else:
                idx += 1
        print('True:',true[trueidx])
        print('---------')
        trueidx+=1

In [21]:
# Function that computes the weighted guess of each array
# Meaning if the array is: [.2 .33 .35 .1 .1] it will guess closer to 2.5 not just 3
def calcRating(arr, true):
    trueIdx = 0
    for row in arr:
        temp = 0
        idx = 1
        for el in row:
            temp = temp + el*idx
            idx += 1
        print('Sample:',trueIdx)
        print('Raw Score out of 5:', temp)
        print('True Score:', true[trueIdx])
        print('++++++++++++++++++')
        trueIdx+=1

In [ ]:
# Counting Number of Each Rating in Output
count5,count4,count3,count2,count1 = 0,0,0,0,0
for rev in Output:
    if rev[0] == 1:
        count1+=1
    elif rev[1] == 1:
        count2+=1
    elif rev[2] == 1:
        count3+=1
    elif rev[3] == 1:
        count4+=1
    else:
        count5+=1
total = count1+count2+count3+count4+count5
print(count1,count2,count3,count4,count5)
print(count1/total,count2/total,count3/total,count4/total,count5/total)

In [ ]:
# Balanced Training Set Generation
count5,count4,count3,count2,count1 = 0,0,0,0,0
print(Output[0][0])
idxArr = []
for i in range(len(Output)):
    if Output[i][0] == 1 and count1 < 749:
        count1 += 1
        idxArr.append(i)
    elif Output[i][1] == 1 and count2 < 749:
        count2 += 1
        idxArr.append(i)
    elif Output[i][2] == 1 and count3 < 749:
        count3 += 1
        idxArr.append(i)
    elif Output[i][3] == 1 and count4 < 749:
        count4 += 1
        idxArr.append(i)
    elif Output[i][4] == 1 and count5 < 749:
        count5 += 1
        idxArr.append(i)

print(idxArr)